### ISSUE TITLE
64-bit installer installs 64-bit binaries into Program Files (x86)

### ISSUE THREAD

**Issue by Owyn** [sylikc/jpegview#100]
I download ` JPEGView64_en-us_1.1.41.msi `, press install, and then boom - I have `C:\Program Files (x86)\JPEGView`

**Comment by sylikc** [comment]
`S:`?  As the install path?

**Comment by sylikc** [comment]
Is the path valid?

**Comment by Owyn** [comment]
> Is the path valid?

path is valid. for a x86 version, and I downloaded a x64 installer

**Comment by sylikc** [comment]
Let me go test... but, does the x86 version do the same thing?  Perhaps I messed up on the naming... I did do the build process in an automated way this time

**Comment by sylikc** [comment]
Let me go test... but, does the x86 version do the same thing?  Perhaps I messed up on the naming... I did do the build process in an automated way this time.  And when I spot-checked, I used the x86 version lol

**Comment by sylikc** [comment]
@Owyn I recall the MSI installer had some detection where it doesn't find the right path... I tested the installer for 1.0.40 and it exhibits the same behavior.

I checked the actual installed files and they're x64 binaries though, so that's correct.

I'll have to look into this later, but it's low priority... there are lots of other x64 apps that get installed into the `Program Files (x86)` directory, especially if the installer has to support 32-bit and 64-bit.

**Comment by pureby** [comment]
I can confirm this issue on **version 1.1.43** (latest as of today) when installing from Winget. `winget install jpegview` installed x64 binaries in `Program Files (x86)` folder.

**Comment by sylikc** [comment]
I just pushed a change that should fix it.  I did some brief testing, and the behavior is
* If JPEGView 64-bit is already installed into `C:\Program Files (x86)`, a new install goes into same location
* On new installs, goes into `C:\Program Files`

It wasn't that easy and feels really hacky... but that's because I have to support both 32-bit and 64-bit in the same installer... but it's the solution that seems to work.  Please test if you get a chance @Owyn @pureby

**Comment by sylikc** [comment]
Please test with the latest [JPEGView nightly](https://github.com/sylikc/jpegview/wiki/Dev-Snapshots#links)

**Comment by pureby** [comment]
Tested `JPEGView-GH_sylikc-Release_x64-149a39e.zip`

4. x64 version installed in `C:\Program Files` on new install 👍 (no previous JPEGView version installed).

**Comment by sylikc** [comment]
Thanks for testing, I appreciate it, gives me a bit more confidence on the release :D

**Comment by pureby** [comment]
You're welcome! I'm happy to help :-)
