### ISSUE TITLE
webp security issue

### ISSUE THREAD

**Issue by makedir** [sylikc/jpegview#240]
Is this fork also effected of the current webp issue? what library does the fork use for webp?

https://blog.isosceles.com/the-webp-0day/
https://nvd.nist.gov/vuln/detail/CVE-2023-4863

**Comment by sylikc** [comment]
Yes the current version is probably affected by the CVE. It's been updated on the current development head but a new version hasn't been pushed out. I expect to get a version out this week.

**Comment by qbnu** [comment]
> Is this fork also effected of the current webp issue?

[Yes](https://github.com/sylikc/jpegview/assets/93988953/7a435421-6dec-42ce-a56d-2e89f4d28d4f)

> what library does the fork use for webp?

[libwebp](https://github.com/webmproject/libwebp)

See #237

**Comment by sylikc** [comment]
Working on it. It's because there's a whole lotta changes on the Dev that I'm testing... and it's sort of all coming at once. 😞

Pushing out just the CVE fix wouldn't do justice to all the work translators and qbnu has put in for this upcoming release 

Luckily, after reading the blog post you attached, a crash in jpegview wouldn't cause a privilege escalation. 😎
