### ISSUE TITLE
[Feature Request] Option for a custom image association icon

### ISSUE THREAD

**Issue by Samillion** [sylikc/jpegview#297]
If JPEGView is set as the default viewer for image association, it uses the EXE icon for the images system wide. An option to allow a custom icon would benefit those with custom aesthetics in the system or ones that simply want to change how the image icons would look like.

**Option:**
- `AssociationIcon=`

**Possible values:**
- default (uses EXE icon)
- Full path (ie: `C:\JPEGView\icon.ico` or `C:\JPEGView\icon.png`)

Note: 
Thank you very much for the excellent work with JPEGView. Can't live without it.

**Comment by TetraTheta** [comment]
As a workaround, you can create your own file association registry entry for custom icon etc.
```batch
reg add "HKCR\JPEGView.PNG" /ve /t REG_SZ /d "PNG File" /f
reg add "HKCR\JPEGView.PNG\DefaultIcon" /ve /t REG_SZ /d "C:\Customizations\custom_icon.dll,19" /f
reg add "HKCR\JPEGView.PNG\shell\open\command" /ve /t REG_SZ /d "\"C:\Program Files\JPEGView\JPEGView.exe\" \"%%1\"" /f
```
For example, this will create `JPEGView.PNG` association that have `C:\Customizations\custom_icon.dll`'s 19th icon as its icon, and run JPEGView when launched.

You must use [SetUserFTA](https://kolbi.cz/blog/2017/10/25/setuserfta-userchoice-hash-defeated-set-file-type-associations-per-user/) for setting file association, because Windows automatically _sets it back_ into Picture app if the registry is manually modified.

If you want to use `ico` file, you can just directly provide `ico` file's location like `C:\Customizations\png.ico` without comma and number after it.

But you can't directly use `png` file as icon. You'll have to convert it into `ico` file. You'll be able to find lots of web service that helps you for it.
