### ISSUE TITLE
win10ltsc2021放大图片拖动卡死，已上传系统日志文件

### ISSUE THREAD

**Issue by kelly-mi** [sylikc/jpegview#97]
系统是windows10 ltsc 2021，屏幕分辨率为4k。
默认全屏模式，放大至超出屏幕，来回拖动2-3次会卡死无响应。非全屏模式，放大至300%左右会无响应。
测试了win7虚拟机内无问题。
[Uploading errorlog.zip…]()

**Comment by sylikc** [comment]
can you tell me the system specs and upload a sample image where this behavior occurs?

**Comment by OCD-Man** [comment]
This looks like the same problem as mentioned in issue #10, which shows that a there are 2 options for a temporary solution, either set CPUType=AutoDetect to CPUType=SSE or set HighQualityResampling=false

It is interesting to see that Windows 7 doesn't have this problem, but I suspect that AVX2 may not be supported by Windows 7 and so maybe the JPEGView setting for CPUType=AutoDetect would be using SSE rather than AVX2. So I found the following webpage with a bit of a discussion on SSE and AVX and apparently Windows 7 only supports AVX with Service Pack 1 installed, but at a quick glance I don't see any responses saying if AVX2 is supported by Windows 7. Do you have Service pack 1 installed on your Windows 7 Virtual machine?

https://stackoverflow.com/questions/34069054/which-versions-of-windows-support-require-which-cpu-multimedia-extensions-how

I couldn't find any difinitive info anywhere that says clearly that Windows 7 supports AVX2. However if it does, maybe wheather Windows 7 is 32bit or 64bit makes a difference.

It would be interesting if you could make sure Service Pack 1 is installed in Windows 7 and if you could force AVX2 to be used in the settings for JPEGView by changing CPUType=AutoDetect to CPUType=AVX2 and see if you can still open any images. If images are no longer able to be opened, then either AVX2 is not supported by Windows 7 or maybe AVX is just not supported by the driver installed for your CPU on Windows 7 since Windows 7 is old and maybe it doesn't have an exact driver for your CPU and maybe the driver installed is only just a compatible driver for your CPU and doesn't support the AVX2 function of your CPU.

It would be good to know if the issue is always just AVX2, or if Windows 7 or 10 is actually makes any difference in JPEGView with AVX2.

Although I wonder if forcing AVX2 in JPEGView also has support for regular AVX and allows regular AVX to be used which would mean that the picture will still load when choosing AVX2 even if AVX2 isn't supported by Windows 7 SP1. Again, if the CPU driver installed on Windows 7 isn't the exact correct driver for that CPU but instead just a compatible driver that doesn't support AVX2 but does support AVX, then forcing AVX2 in JPEGView may still load the picture and you wouldn't know if it is AVX or AVX2 being used by JPEGView and it wouldn't say if AVX2 is compatible with Windows 7 or not. Only if it happens to be that pictures don't load at all after forcing AVX2 in JPEGView can it be seen that Windows 7 SP1 or the CPU driver doesn't support AVX2, but still unknown if Windows 7 doesn't support AVX2 or if it is the CPU driver that doesn't support for AVX2.

Actually I found a couple of programs that will tell you if AVX2 is supported such as HWinfo or CPU-Z. Although I don't know if it takes into account the operating system and the CPU driver, but I assume it should. HWinfo will highlight AVX2 in green if it is supported, otherwise it will be grey. This may be a good way to see if AVX2 is being used in kelly-mi Windows 7 virtual machine. But in this case it will only be certain that Windows 7 does support AVX2 if AVX2 shows up as being supported, and if the program doesn`t show AVX2, then maybe it is just the driver for the CPU.

I don't have a processor that supports AVX2 so I can't check if Windows 7 with Service Pack 1 installed supports AVX2 by forcing JPEGView to use AVX2 and seeing if an image will load. sylikc, maybe you have an installation of Windows 7 with SP1 with a processor that supports AVX2.

Here is a microsoft webpage about AVX added to Windows 7 in SP1 in case it helps in any way:
https://learn.microsoft.com/en-us/windows/win32/win7appqual/enable-windows-7-support-for-intel-avx

The info highlighted in purple on the webpage from the following link says that AVX2 introduces FMA, but the above microsoft.com link doesn't mention anything about AVX2 or FMA which makes  me assume AVX2 isn't supported by Windows 7.

https://milvus.io/blog/milvus-performance-AVX-512-vs-AVX2.md#:~:text=AVX%20introduced%20a%20new%20coding,extension%20(EVEX)%20prefix%20encoding.

I also just added another comment in issue #10 to point out a possibility that this problem occurs when JPEGView attempts to use over 50mb. More details are in that comment.

**Comment by kelly-mi** [comment]
<img width="960" alt="无标题" src="https://user-images.githubusercontent.com/37164210/222500019-962101c6-7aa2-4093-82eb-a408b614e1cf.png">

i tested the latest revision 1.1.44, the bug exists still。

https://wwxt.lanzout.com/izh4E0p30tng

url is video demonstrating this problem。

**Comment by sylikc** [comment]
@kelly-mi can you test the suggestion here?

https://github.com/sylikc/jpegview/issues/53#issuecomment-1164165618
> Right click the exe, go to properties, then the compatibility tab, and click on "Change High DPI settings." From there, check the box for "Override high DPI scaling behavior" and select "System" from the drop-down box

If it fixes the crashing I think we've figured out the common reason

**Comment by sylikc** [comment]
v1.2.45 has been released that fixes this issue.  You should be able to undo the changes to HiDPI settings, and CPUType/HighQualityResampling INI options.  Please reopen issue if crash/freeze still happens.
